/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DamithT
 */
public class CashierDashboard extends javax.swing.JFrame {

    /**
     * Creates new form CashierDashboard
     */
    public CashierDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnViewSearch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLogoutCash = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMainBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 40)); // NOI18N
        lblTitle.setText("Cashier Dashboard");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(60, 100, 330, 47);

        btnViewSearch.setBackground(new java.awt.Color(102, 204, 255));
        btnViewSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        btnViewSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewSearch.setPreferredSize(new java.awt.Dimension(260, 260));
        btnViewSearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnViewSearchMouseMoved(evt);
            }
        });
        btnViewSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewSearchMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel2.setText("View & Search ");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-view-96.png"))); // NOI18N

        javax.swing.GroupLayout btnViewSearchLayout = new javax.swing.GroupLayout(btnViewSearch);
        btnViewSearch.setLayout(btnViewSearchLayout);
        btnViewSearchLayout.setHorizontalGroup(
            btnViewSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnViewSearchLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnViewSearchLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(btnViewSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49))
        );
        btnViewSearchLayout.setVerticalGroup(
            btnViewSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnViewSearchLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
        );

        getContentPane().add(btnViewSearch);
        btnViewSearch.setBounds(60, 230, 280, 260);

        btnLogoutCash.setBackground(new java.awt.Color(102, 204, 255));
        btnLogoutCash.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        btnLogoutCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoutCash.setPreferredSize(new java.awt.Dimension(260, 260));
        btnLogoutCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutCashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutCashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutCashMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-logout-96.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel4.setText("Logout");

        javax.swing.GroupLayout btnLogoutCashLayout = new javax.swing.GroupLayout(btnLogoutCash);
        btnLogoutCash.setLayout(btnLogoutCashLayout);
        btnLogoutCashLayout.setHorizontalGroup(
            btnLogoutCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogoutCashLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(btnLogoutCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        btnLogoutCashLayout.setVerticalGroup(
            btnLogoutCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutCashLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(btnLogoutCash);
        btnLogoutCash.setBounds(720, 230, 280, 260);

        btnOrder.setBackground(new java.awt.Color(102, 204, 255));
        btnOrder.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.setPreferredSize(new java.awt.Dimension(260, 260));
        btnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrderMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel6.setText("Order Products");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-purchase-order-96.png"))); // NOI18N

        javax.swing.GroupLayout btnOrderLayout = new javax.swing.GroupLayout(btnOrder);
        btnOrder.setLayout(btnOrderLayout);
        btnOrderLayout.setHorizontalGroup(
            btnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOrderLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(49, 49, 49))
            .addGroup(btnOrderLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(btnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnOrderLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        btnOrderLayout.setVerticalGroup(
            btnOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOrderLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(47, 47, 47))
        );

        getContentPane().add(btnOrder);
        btnOrder.setBounds(390, 230, 280, 260);
        getContentPane().add(lblMainBg);
        lblMainBg.setBounds(0, 0, 1080, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSearchMouseEntered
        // TODO add your handling code here:
         btnViewSearch.setBackground(Color.white);
         jLabel2.setForeground(Color.red);
    }//GEN-LAST:event_btnViewSearchMouseEntered

    private void btnViewSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSearchMouseExited
        // TODO add your handling code here:
        btnViewSearch.setBackground(Color.decode("#64B5F6"));
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_btnViewSearchMouseExited

    private void btnLogoutCashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutCashMouseEntered
        // TODO add your handling code here:
        btnLogoutCash.setBackground(Color.white);
        jLabel4.setForeground(Color.red);
    }//GEN-LAST:event_btnLogoutCashMouseEntered

    private void btnLogoutCashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutCashMouseExited
        // TODO add your handling code here:
        btnLogoutCash.setBackground(Color.decode("#64B5F6"));
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_btnLogoutCashMouseExited

    private void btnLogoutCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutCashMouseClicked
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
        new Signin().setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_btnLogoutCashMouseClicked

    private void btnViewSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSearchMouseClicked
        // TODO add your handling code here:
            CashierView jfCV = new CashierView();
            jfCV.setVisible(true); // Display the sign-in frame
            dispose(); // Close the current (dashboard) frame
        
    }//GEN-LAST:event_btnViewSearchMouseClicked

    private void btnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseClicked
        // TODO add your handling code here:
            Order od1 = new Order();
            od1.setVisible(true); // Display the sign-in frame
            dispose();
    }//GEN-LAST:event_btnOrderMouseClicked

    private void btnOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseEntered
        // TODO add your handling code here:
        btnOrder.setBackground(Color.white);
        jLabel6.setForeground(Color.red);
    }//GEN-LAST:event_btnOrderMouseEntered

    private void btnOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrderMouseExited
        // TODO add your handling code here:
        btnOrder.setBackground(Color.decode("#64B5F6"));
        jLabel6.setForeground(Color.black);
    }//GEN-LAST:event_btnOrderMouseExited

    private void btnViewSearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSearchMouseMoved
    }//GEN-LAST:event_btnViewSearchMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLogoutCash;
    private javax.swing.JPanel btnOrder;
    private javax.swing.JPanel btnViewSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblMainBg;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
