/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Manager;
import Model.Products;
//import View.ManagerDashboard;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
//import java.sql.Statement;
import javax.swing.JOptionPane;
//import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableRowSorter;
//import Model.database;

/**
 *
 * @author DamithT
 */
public class ManagerView extends javax.swing.JFrame {
    
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    Manager manager1 = new Manager();

    /**
     * Creates new form ManagerDashboard
     */
    public ManagerView() {
        initComponents();
        txtSearch.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtProductId.setBackground(new java.awt.Color(0, 0, 0, 1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGoBackManview = new javax.swing.JButton();
        lblProduct = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        lblCat = new javax.swing.JLabel();
        cmbProductCat = new javax.swing.JComboBox<>();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblProductId = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 720));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setText("Mange Stocks");

        btnGoBackManview.setBackground(new java.awt.Color(2, 121, 239));
        btnGoBackManview.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnGoBackManview.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBackManview.setText("Go Back");
        btnGoBackManview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBackManview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackManviewActionPerformed(evt);
            }
        });

        lblProduct.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblProduct.setText("Product");

        txtProductId.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtProductId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        txtProductId.setPreferredSize(new java.awt.Dimension(0, 21));

        lblCat.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblCat.setText("Category");

        cmbProductCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbProductCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Select Category----", "iPhone", "Mac", "Apple Watch", "TV & Home", "iPad", "Accessories", "Airpods", "Vision", "AirTag" }));

        lblPrice.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblPrice.setText("Price");

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        txtPrice.setPreferredSize(new java.awt.Dimension(0, 21));

        btnUpdate.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(2, 121, 239));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(80, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 25));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 153, 0));
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(80, 25));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 51, 51));
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(80, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblProductId.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblProductId.setText("Product ID");

        txtProduct.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        txtProduct.setPreferredSize(new java.awt.Dimension(0, 21));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnGoBackManview, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cmbProductCat, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCat)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProduct)
                            .addComponent(lblProductId)
                            .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(lblProductId)
                .addGap(12, 12, 12)
                .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProductCat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addGap(1, 1, 1)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGoBackManview, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 720);

        tblStock.setBackground(new java.awt.Color(158, 255, 248));
        tblStock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 121, 239)));
        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Product", "Category", "$ Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 160, 590, 470);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        txtSearch.setPreferredSize(new java.awt.Dimension(0, 21));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch);
        txtSearch.setBounds(700, 80, 320, 40);

        lblSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblSearch.setText("Type any keyword to Search");
        getContentPane().add(lblSearch);
        lblSearch.setBounds(410, 80, 290, 32);

        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\shake\\Downloads\\bg1 (1).jpg")); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1130, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:     
        manager1.viewProduct(tblStock);
    }//GEN-LAST:event_formWindowOpened

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        manager1.searchProduct(tblStock, search);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnGoBackManviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackManviewActionPerformed
        // TODO add your handling code here:
        ManagerDashboard jfMDash = new ManagerDashboard();
        jfMDash.setVisible(true); // Display the sign-in frame
        dispose(); // Close the current (dashboard) frame

    }//GEN-LAST:event_btnGoBackManviewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        // TODO add your handling code here:
        String productId = txtProductId.getText().trim();
        String productName = txtProduct.getText().trim();
        String price = txtPrice.getText().trim();
        String productCat = cmbProductCat.getSelectedItem().toString();
        
        if (productId.isEmpty() || productName.isEmpty() || price.isEmpty() || productCat.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "You can't add an item with empty details!");
            // format validation
        } else if (!productId.matches("iST/P/\\d{3}")) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Product ID Format! Please use iST/P/001 format.");
            return;// 

        } else {
            if (manager1.isProductExists(productId)) {
                JOptionPane.showMessageDialog(rootPane, "Product ID already exists! Please choose a different ID.");
                return; // 
            } else {
                Products product = new Products(productId, productName, productCat, price);
                manager1.addProduct(product);
                
                JOptionPane.showMessageDialog(rootPane, "Item Added Successfully");
                manager1.viewProduct(tblStock);
            }
        }
        txtProductId.setText("");
        txtProduct.setText("");
        cmbProductCat.setSelectedItem("----Select Category----");
        txtPrice.setText("");

    }//GEN-LAST:event_btnAddActionPerformed

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        //set data to text fields
        DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();

        //set data to text field when raw is selected
        String pid = tblModel.getValueAt(tblStock.getSelectedRow(), 0).toString();
        String prod = tblModel.getValueAt(tblStock.getSelectedRow(), 1).toString();
        String cat = tblModel.getValueAt(tblStock.getSelectedRow(), 2).toString();
        String pric = tblModel.getValueAt(tblStock.getSelectedRow(), 3).toString();

        //set to input fields
        txtProductId.setText(pid);
        txtProduct.setText(prod);
        cmbProductCat.setSelectedItem(cat);
        txtPrice.setText(pric);
        btnAdd.setEnabled(false);
        txtProductId.setEnabled(false);

    }//GEN-LAST:event_tblStockMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here
        int selectedRow = tblStock.getSelectedRow();
        DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();
        
        if (selectedRow >= 0) {
            String productId = txtProductId.getText();
            String productName = txtProduct.getText();
            String productCat = cmbProductCat.getSelectedItem().toString();
            String price = txtPrice.getText();
            String id = tblModel.getValueAt(selectedRow, 0).toString(); // Assuming the ID is in the first column

            Products product = new Products(productId, productName, productCat, price);
            manager1.updateProduct(product, id);
            JOptionPane.showMessageDialog(rootPane, "Item Updated Successfully");
            btnAdd.setEnabled(true);
            txtProductId.setText("");
            txtProduct.setText("");
            cmbProductCat.setSelectedItem("----Select Category----");
            txtPrice.setText("");
            manager1.viewProduct(tblStock);
        } else {
            // No row selected, so deactivate the update button
            btnAdd.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Select a row to update.");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtProductId.setText("");
        txtProduct.setText("");
        cmbProductCat.setSelectedItem("----Select Category----");
        txtPrice.setText("");
        btnAdd.setEnabled(true);
        txtProductId.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStock.getSelectedRow();
        DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();
        
        if (selectedRow >= 0) {
            String id = (tblModel.getValueAt(selectedRow, 0).toString());
            
            int rowsDeleted = manager1.deleteProduct(id);
            if (rowsDeleted > 0) {
                // Remove the selected row from the table in the GUI
                tblModel.removeRow(selectedRow);
                
                JOptionPane.showMessageDialog(rootPane, "Item Deleted Successfully");
                btnAdd.setEnabled(true);
                txtProductId.setText("");
                txtProduct.setText("");
                cmbProductCat.setSelectedItem("----Select Category----");
                txtPrice.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Failed to delete the item.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Select a row to delete.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoBackManview;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbProductCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    
}
