/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.CreateAcc;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DamithT
 */
public class ManagerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form ManagerDashboard
     */
    public ManagerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCreateAcc = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnManageItems = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogoutDash = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMainBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 0, 40)); // NOI18N
        lblTitle.setText("Manager Dashboard");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(80, 100, 360, 47);

        btnCreateAcc.setBackground(new java.awt.Color(102, 204, 255));
        btnCreateAcc.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        btnCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAcc.setPreferredSize(new java.awt.Dimension(260, 260));
        btnCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateAccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateAccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateAccMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-create-96.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel6.setText("Create Account");

        javax.swing.GroupLayout btnCreateAccLayout = new javax.swing.GroupLayout(btnCreateAcc);
        btnCreateAcc.setLayout(btnCreateAccLayout);
        btnCreateAccLayout.setHorizontalGroup(
            btnCreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreateAccLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(btnCreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCreateAccLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCreateAccLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        btnCreateAccLayout.setVerticalGroup(
            btnCreateAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreateAccLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(btnCreateAcc);
        btnCreateAcc.setBounds(400, 240, 280, 260);

        btnManageItems.setBackground(new java.awt.Color(102, 204, 255));
        btnManageItems.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        btnManageItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageItems.setPreferredSize(new java.awt.Dimension(260, 260));
        btnManageItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageItemsMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel2.setText("Manage Items");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-account-96.png"))); // NOI18N

        javax.swing.GroupLayout btnManageItemsLayout = new javax.swing.GroupLayout(btnManageItems);
        btnManageItems.setLayout(btnManageItemsLayout);
        btnManageItemsLayout.setHorizontalGroup(
            btnManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManageItemsLayout.createSequentialGroup()
                .addGroup(btnManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnManageItemsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(btnManageItemsLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnManageItemsLayout.setVerticalGroup(
            btnManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnManageItemsLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(btnManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
        );

        getContentPane().add(btnManageItems);
        btnManageItems.setBounds(80, 240, 280, 260);

        btnLogoutDash.setBackground(new java.awt.Color(102, 204, 255));
        btnLogoutDash.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 255)));
        btnLogoutDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoutDash.setPreferredSize(new java.awt.Dimension(260, 260));
        btnLogoutDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutDashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutDashMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons8-logout-96.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel4.setText("Logout");

        javax.swing.GroupLayout btnLogoutDashLayout = new javax.swing.GroupLayout(btnLogoutDash);
        btnLogoutDash.setLayout(btnLogoutDashLayout);
        btnLogoutDashLayout.setHorizontalGroup(
            btnLogoutDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutDashLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(btnLogoutDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogoutDashLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogoutDashLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        btnLogoutDashLayout.setVerticalGroup(
            btnLogoutDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutDashLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(btnLogoutDash);
        btnLogoutDash.setBounds(720, 240, 280, 260);
        getContentPane().add(lblMainBg);
        lblMainBg.setBounds(0, 0, 1080, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageItemsMouseClicked
        // TODO add your handling code here:
        ManagerView jfMV = new ManagerView();
        jfMV.setVisible(true); // Display the sign-in frame
        dispose(); // Close the current (dashboard) frame

    }//GEN-LAST:event_btnManageItemsMouseClicked

    private void btnManageItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageItemsMouseEntered
        // TODO add your handling code here:
        btnManageItems.setBackground(Color.white);
        jLabel2.setForeground(Color.red);
    }//GEN-LAST:event_btnManageItemsMouseEntered

    private void btnManageItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageItemsMouseExited
        // TODO add your handling code here:
        btnManageItems.setBackground(Color.decode("#3993ED"));
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_btnManageItemsMouseExited

    private void btnLogoutDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutDashMouseClicked
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            //this.setVisible(false);
            new Signin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutDashMouseClicked

    private void btnLogoutDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutDashMouseEntered
        // TODO add your handling code here:
        btnLogoutDash.setBackground(Color.white);
        jLabel4.setForeground(Color.red);
    }//GEN-LAST:event_btnLogoutDashMouseEntered

    private void btnLogoutDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutDashMouseExited
        // TODO add your handling code here:
        btnLogoutDash.setBackground(Color.decode("#3993ED"));
        jLabel4.setForeground(Color.black);
    }//GEN-LAST:event_btnLogoutDashMouseExited

    private void btnCreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAccMouseClicked
        // TODO add your handling code here:
        CreateAcc jfAcc = new CreateAcc();
        jfAcc.setVisible(true); // Display the sign-in frame
        dispose(); // Close the current (dashboard) frame
    }//GEN-LAST:event_btnCreateAccMouseClicked

    private void btnCreateAccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAccMouseEntered
        // TODO add your handling code here:
        btnCreateAcc.setBackground(Color.white);
        jLabel6.setForeground(Color.red);
    }//GEN-LAST:event_btnCreateAccMouseEntered

    private void btnCreateAccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAccMouseExited
        // TODO add your handling code here:
        btnCreateAcc.setBackground(Color.decode("#3993ED"));
        jLabel6.setForeground(Color.black);
    }//GEN-LAST:event_btnCreateAccMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCreateAcc;
    private javax.swing.JPanel btnLogoutDash;
    private javax.swing.JPanel btnManageItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblMainBg;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
