/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Cashier;
import Controller.Manager;
import Model.Products;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DamithT
 */
public class Order extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    Manager manager1 = new Manager();
    Cashier cashier1 = new Cashier("", "", "", "", "");

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        txtPId.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtProduct.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtCat.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtPrice.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMakeOrder = new javax.swing.JLabel();
        lblPId = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtPId = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();
        txtCat = new javax.swing.JTextField();
        btnAddToList = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblMakeOrder1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStock = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        lblProdList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdded = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        lblAdded = new javax.swing.JLabel();
        btnPrintInvoice = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        lblBackBtn = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaInvoice = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 945));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblMakeOrder.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblMakeOrder.setText("Make Order");
        getContentPane().add(lblMakeOrder);
        lblMakeOrder.setBounds(120, 40, 190, 42);

        lblPId.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblPId.setText("Product Id");
        getContentPane().add(lblPId);
        lblPId.setBounds(30, 120, 130, 32);

        lblProduct.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblProduct.setText("Product");
        getContentPane().add(lblProduct);
        lblProduct.setBounds(30, 180, 100, 32);

        lblCat.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblCat.setText("Category");
        getContentPane().add(lblCat);
        lblCat.setBounds(30, 240, 140, 32);

        lblPrice.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblPrice.setText("Price in $");
        getContentPane().add(lblPrice);
        lblPrice.setBounds(30, 310, 120, 29);

        txtPId.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        getContentPane().add(txtPId);
        txtPId.setBounds(30, 140, 280, 40);

        txtProduct.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        getContentPane().add(txtProduct);
        txtProduct.setBounds(30, 200, 280, 40);

        txtCat.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtCat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        getContentPane().add(txtCat);
        txtCat.setBounds(30, 270, 280, 40);

        btnAddToList.setBackground(new java.awt.Color(2, 121, 239));
        btnAddToList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddToList.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToList.setText("Add To List");
        btnAddToList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToListActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToList);
        btnAddToList.setBounds(70, 390, 190, 40);

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(2, 121, 239)));
        getContentPane().add(txtPrice);
        txtPrice.setBounds(30, 330, 280, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 125, 226));
        jSeparator1.setForeground(new java.awt.Color(0, 125, 226));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 450, 1030, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 125, 226));
        jSeparator2.setForeground(new java.awt.Color(0, 125, 226));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(600, 470, 20, 420);

        lblMakeOrder1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblMakeOrder1.setText("$");
        getContentPane().add(lblMakeOrder1);
        lblMakeOrder1.setBounds(400, 750, 20, 42);

        tblStock.setBackground(new java.awt.Color(158, 255, 248));
        tblStock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 121, 239)));
        tblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Product", "Category", "$ Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStock);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 90, 580, 330);

        jSeparator3.setBackground(new java.awt.Color(0, 125, 226));
        jSeparator3.setForeground(new java.awt.Color(0, 125, 226));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(430, 70, 20, 360);

        lblProdList.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblProdList.setText("Product List");
        getContentPane().add(lblProdList);
        lblProdList.setBounds(650, 30, 230, 42);

        tblAdded.setBackground(new java.awt.Color(158, 255, 248));
        tblAdded.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 121, 239)));
        tblAdded.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product", "Category", "$ Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAdded);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 520, 550, 220);

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txtTotal);
        txtTotal.setBounds(430, 750, 140, 40);

        lblAdded.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblAdded.setText("Added Items");
        getContentPane().add(lblAdded);
        lblAdded.setBounds(210, 470, 230, 42);

        btnPrintInvoice.setBackground(new java.awt.Color(255, 255, 255));
        btnPrintInvoice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrintInvoice.setForeground(new java.awt.Color(0, 0, 255));
        btnPrintInvoice.setText("Print Invoice");
        btnPrintInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintInvoiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrintInvoice);
        btnPrintInvoice.setBounds(220, 760, 150, 50);

        btnRemoveItem.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemoveItem.setForeground(new java.awt.Color(255, 0, 0));
        btnRemoveItem.setText("Remove Item");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveItem);
        btnRemoveItem.setBounds(30, 760, 150, 50);

        lblBackBtn.setBackground(new java.awt.Color(255, 255, 255));
        lblBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBackBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        lblBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackBtnMouseExited(evt);
            }
        });
        getContentPane().add(lblBackBtn);
        lblBackBtn.setBounds(30, 40, 40, 40);

        txtAreaInvoice.setColumns(20);
        txtAreaInvoice.setRows(5);
        jScrollPane3.setViewportView(txtAreaInvoice);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(620, 470, 410, 420);

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(220, 820, 150, 50);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 820, 150, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStockMouseClicked
        //set data to text fields
        DefaultTableModel tblModel = (DefaultTableModel) tblStock.getModel();

        String productId = tblModel.getValueAt(tblStock.getSelectedRow(), 0).toString();
        String productName = tblModel.getValueAt(tblStock.getSelectedRow(), 1).toString();
        String productCat = tblModel.getValueAt(tblStock.getSelectedRow(), 2).toString();
        String productPrice = tblModel.getValueAt(tblStock.getSelectedRow(), 3).toString();

        txtPId.setText(productId);
        txtProduct.setText(productName);
        txtCat.setText(productCat);
        txtPrice.setText(productPrice);
    }//GEN-LAST:event_tblStockMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        manager1.viewProduct(tblStock);
    }//GEN-LAST:event_formWindowOpened

    private void lblBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackBtnMouseClicked
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to Go Back?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {

            CashierDashboard jfCDash = new CashierDashboard();
            jfCDash.setVisible(true); // Display the sign-in frame
            dispose(); // Close the current (dashboard) frame
        }


    }//GEN-LAST:event_lblBackBtnMouseClicked

    private void lblBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackBtnMouseEntered
        // TODO add your handling code here:
        lblBackBtn.setSize(new java.awt.Dimension(48, 48));
    }//GEN-LAST:event_lblBackBtnMouseEntered

    private void lblBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackBtnMouseExited
        // TODO add your handling code here:
        lblBackBtn.setSize(new java.awt.Dimension(40, 40));
    }//GEN-LAST:event_lblBackBtnMouseExited

    private void btnAddToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToListActionPerformed
        if (txtPId.getText().isEmpty() || txtProduct.getText().isEmpty() || txtCat.getText().isEmpty() || txtPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "!!! You can't add Item with Empty Details");
        } else {
            DefaultTableModel tableModel = (DefaultTableModel) tblAdded.getModel();

            String[] rowData = new String[4];

            rowData[0] = txtPId.getText();
            rowData[1] = txtProduct.getText();
            rowData[2] = txtCat.getText();
            rowData[3] = txtPrice.getText();

            tableModel.addRow(rowData);

            // Clear text fields after adding the row
            txtPId.setText("");
            txtProduct.setText("");
            txtCat.setText("");
            txtPrice.setText("");

            // Remove item from tblStock
            DefaultTableModel stockTableModel = (DefaultTableModel) tblStock.getModel();
            int selectedRowStock = tblStock.getSelectedRow();
            if (selectedRowStock != -1) {
                // Get the product ID from the selected row

             String id = stockTableModel.getValueAt(selectedRowStock, 0).toString();

                // Delete the product with the given ID from the database
                int rowsDeletedFromDB = manager1.deleteProduct(id);

                if (rowsDeletedFromDB > 0) {
                    //  remove the selected row from the table in the GUI
                    stockTableModel.removeRow(selectedRowStock);
                }
            }
            // calculate the total in tblAdded
            cashier1.calTotal(tblAdded, txtTotal);
        }

    }//GEN-LAST:event_btnAddToListActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        // TODO add your handling code here:

        DefaultTableModel tableModelAdded = (DefaultTableModel) tblAdded.getModel();
        DefaultTableModel tableModelStock = (DefaultTableModel) tblStock.getModel();

        if (tblAdded.getSelectedRow() >= 0) {
            int selectedRow = tblAdded.getSelectedRow();

            //Get data from selected row in tblAdded
            Vector<Object> rowData = new Vector<>();
            for (int i = 0; i < tableModelAdded.getColumnCount(); i++) {
                rowData.add(tableModelAdded.getValueAt(selectedRow, i));
            }

            // Add data to tblStock
            tableModelStock.addRow(rowData);

            // Remove the row from tblAdded
            tableModelAdded.removeRow(selectedRow);

            if (tblAdded.getRowCount() == 0) {
                txtTotal.setText("0.00");
            } else {
                cashier1.calTotal(tblAdded, txtTotal);
            }
            Products product = new Products(rowData.get(0).toString(), rowData.get(1).toString(), rowData.get(2).toString(), rowData.get(3).toString());

            manager1.addProduct(product);
        }


    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnPrintInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintInvoiceActionPerformed
        // TODO add your handling code here:
        cashier1.printInvoice(tblAdded, txtAreaInvoice, txtTotal);

    }//GEN-LAST:event_btnPrintInvoiceActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtAreaInvoice.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CashierDashboard jfCDash = new CashierDashboard();
            jfCDash.setVisible(true); // Display the sign-in frame
            dispose(); // Close the current (dashboard) frame
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToList;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrintInvoice;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAdded;
    private javax.swing.JLabel lblBackBtn;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblMakeOrder;
    private javax.swing.JLabel lblMakeOrder1;
    private javax.swing.JLabel lblPId;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProdList;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JTable tblAdded;
    private javax.swing.JTable tblStock;
    private javax.swing.JTextArea txtAreaInvoice;
    private javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtPId;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
